services:
  gateway-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: frostfire-gateway-dev
    restart: unless-stopped
    ports:
      - "8080:8080"
      - "9999:9999"
      - "8443:8443"
      - "9998:9998"
    volumes:
      - ./.env.development:/app/.env.development:ro
    env_file:
      - .env.development
    networks:
      - gateway-network-dev

networks:
  gateway-network-dev:
    driver: bridge
